general {
  lock_cmd = pidof hyprlock || hyprlock & sleep 1 && hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
  unlock_cmd = pkill -USR1 hyprlock; hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
  before_sleep_cmd = pidof hyprlock || hyprlock
}
