general {
  lock_cmd = pidof hyprlock || hyprlock & sleep 1 && hyprctl dispatch dpms off
  unlock_cmd = pkill -USR1 hyprlock; hyprctl dispatch dpms on
  before_sleep = loginctl lock-session
  after_sleep = hyprctl dispatch dpms on
}
