general {
  lock_cmd = if ! pidof hyprlock; then hyprlock & (sleep 600 && systemctl suspend) & echo "$!" > /tmp/sleep.pid; fi
  unlock_cmd = pkill -USR1 hyprlock; if [[ -f /tmp/sleep.pid ]]; then pkill -F /tmp/sleep.pid; rm /tmp/sleep.pid; fi
  before_sleep_cmd = pidof hyprlock || hyprlock
}
