[window]
opacity = 0.5

[colors]
primary = { foreground = "#DDDDDD", background = "#000000" }
cursor = { text = "#111111", cursor = "#DDDDDD" }
vi_mode_cursor = { text = "#111111", cursor = "#DDDDDD" }
line_indicator = { foreground = "#DDDDDD", background = "#333333" }
footer_bar = { foreground = "#DDDDDD", background = "#333333" }
selection = { text = "#DDDDDD", background = "#001F3F" }

[colors.search]
matches = { foreground = "#111111", background = "#FF4136" }
focused_match = { foreground = "#111111", background = "#FFDC00" }

[colors.normal]
black = "#111111"
red = "#FF4136"
green = "#2ECC40"
yellow = "#FFDC00"
blue = "#0074D9"
magenta = "#F012BE"
cyan = "#7FDBFF"
white = "#FFFFFF"

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 500
thickness = 0.2
