[commit]
  gpgSign = true

[fetch]
  all = true
  prune = true

[init]
  defaultBranch = main

[pull]
  rebase = true

[push]
  autoSetupRemote = true

[rebase]
  autoStash = true

[submodule]
  recurse = true

[user]
  email = pdiehm8@gmail.com
  name = Pascal Diehm
  signingKey = 0xE85EB0566C779A2F

; vim: ft=gitconfig
