fields=0 48 6 18 38 39 40 2 46 47 49 1
hide_userland_threads=1
hide_running_in_container=1
show_program_path=0
highlight_base_name=1
highlight_changes=1
screen_tabs=0
show_cpu_frequency=1
enable_mouse=0
delay=10
column_meters_0=LeftCPUs4 Memory Swap GPU DiskIO NetworkIO
column_meter_modes_0=1 1 1 1 2 2
column_meters_1=RightCPUs4 Tasks LoadAverage Uptime Systemd SystemdUser
column_meter_modes_1=1 2 2 2 2 2
tree_view=1
screen:Main=PID USER TTY NICE M_VIRT M_RESIDENT M_SHARE STATE PERCENT_CPU PERCENT_MEM TIME Command
