scrollback_pager_history_size 128
background_opacity 0.5

background #000000
foreground #DDDDDD

selection_background #AAAAAA
selection_foreground #111111

color0 #111111
color1 #FF4136
color2 #2ECC40
color3 #FFDC00
color4 #0074D9
color5 #F012BE
color6 #7FDBFF
color7 #FFFFFF
