timeout: 0

/Arch
  protocol: linux
  path: boot():/vmlinuz-linux
  cmdline: rw root=LABEL=root rootflags=subvol=root cryptdevice=/dev/disk/by-partlabel/root:root
  module_path: boot():/$UCODE
  module_path: boot():/initramfs-linux.img
