timeout: 0

/Arch
  protocol: linux
  path: boot():/vmlinuz-@KERNEL@
  cmdline: rw root=LABEL=root rootflags=subvol=root cryptdevice=/dev/disk/by-partlabel/root:root
  module_path: boot():/@CPU@-ucode.img
  module_path: boot():/initramfs-@KERNEL@.img
