font=Noto Sans 10
background-color=#111111
text-color=#DDDDDD
border-color=#0074D9
border-radius=5
progress-color=over #001F3F
default-timeout=5000

[urgency=critical]
border-color=#FF4136

[urgency=low]
border-color=#AAAAAA
