table inet filter {
  chain input {
    type filter hook input priority filter
    policy drop

    iif lo accept
    ct state invalid drop
    ct state { established, related } accept
    meta l4proto { icmp, icmpv6 } accept

    tcp dport { 1234, 1970 } accept
  }

  chain forward {
    type filter hook forward priority filter
    policy drop
  }
}
