destroy table inet filter

table inet filter {
  chain input {
    type filter hook input priority filter
    policy drop

    ct state invalid drop
    ct state { established, related } accept
    meta iif lo accept
    meta l4proto { icmp, icmpv6 } accept
    tcp dport { $TCP } accept
    udp dport { $UDP } accept
  }

  chain forward {
    type filter hook forward priority filter
    policy drop

    iifname { "docker0", "br-*" } accept
    oifname { "docker0", "br-*" } accept
    iifname "wg" oifname "wg" accept
  }
}
