new-session -A -s 0

set -g default-terminal tmux-256color
set -g renumber-windows on

bind -n M-d detach
bind -n M-Space choose-tree -Zw

bind -n M-w split-window -h
bind -n M-W split-window
bind -n M-t new-window

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n C-M-h resize-pane -L
bind -n C-M-j resize-pane -D
bind -n C-M-k resize-pane -U
bind -n C-M-l resize-pane -R

bind -n M-Tab next-window
bind -n M-BTab previous-window
