[Login]
IdleAction=sleep
IdleActionSec=1h
HandlePowerKey=sleep
HandlePowerKeyLongPress=ignore
HandleRebootKey=ignore
HandleRebootKeyLongPress=ignore
HandleSuspendKey=suspend
HandleSuspendKeyLongPress=ignore
HandleHibernateKey=ignore
HandleHibernateKeyLongPress=ignore
HandleLidSwitch=sleep
HandleLidSwitchExternalPower=sleep
HandleLidSwitchDocked=ignore
