vim.keymap.set({ "n", "x", "t" }, "<A-w>", "<Cmd>vertical new<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-W>", "<Cmd>new<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-s>", "<Cmd>vertical split<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-S>", "<Cmd>split<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-t>", "<Cmd>tab new<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-T>", "<Cmd>wincmd T<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-o>", "<Cmd>only<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-h>", "<Cmd>wincmd h<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-j>", "<Cmd>wincmd j<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-k>", "<Cmd>wincmd k<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-l>", "<Cmd>wincmd l<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-H>", "<Cmd>wincmd H<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-J>", "<Cmd>wincmd J<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-K>", "<Cmd>wincmd K<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-L>", "<Cmd>wincmd L<CR>")
vim.keymap.set({ "n", "x", "t" }, "<C-A-h>", "<Cmd>wincmd <<CR>")
vim.keymap.set({ "n", "x", "t" }, "<C-A-l>", "<Cmd>wincmd ><CR>")
vim.keymap.set({ "n", "x", "t" }, "<C-A-k>", "<Cmd>wincmd +<CR>")
vim.keymap.set({ "n", "x", "t" }, "<C-A-j>", "<Cmd>wincmd -<CR>")
vim.keymap.set({ "n", "x", "t" }, "<C-A-Space>", "<Cmd>wincmd =<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-Tab>", "<Cmd>tabnext<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-S-Tab>", "<Cmd>tabprevious<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-1>", "<Cmd>tabnext 1<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-2>", "<Cmd>tabnext 2<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-3>", "<Cmd>tabnext 3<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-4>", "<Cmd>tabnext 4<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-5>", "<Cmd>tabnext 5<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-6>", "<Cmd>tabnext 6<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-7>", "<Cmd>tabnext 7<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-8>", "<Cmd>tabnext 8<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-9>", "<Cmd>tabnext 9<CR>")

vim.keymap.set("n", "g0", "gg0")
vim.keymap.set("n", "gl", "<C-o>")
vim.keymap.set("n", "gq", "<Cmd>cnext<CR>")
vim.keymap.set("n", "gQ", "<Cmd>cprev<CR>")
vim.keymap.set("n", "gs", "]s")
vim.keymap.set("n", "gS", "[s")

vim.keymap.set("x", "H", "<gv")
vim.keymap.set("x", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("x", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("x", "L", ">gv")
vim.keymap.set("x", "O", ":sort<CR>")

vim.keymap.set("n", "<Space><Return>", "<Cmd>terminal<CR>i")
vim.keymap.set("t", "<A-Esc>", "<C-\\><C-n>")
vim.keymap.set("t", "<C-BS>", "<C-h>")

vim.keymap.set("!", "<C-BS>", "<C-w>")
vim.keymap.set("n", "<C-j>", "m`J``")
vim.keymap.set("n", "X", '"_D')
vim.keymap.set("n", "vv", "gv")
vim.keymap.set({ "n", "x" }, "x", '"_x')

vim.keymap.del("n", "gra")
vim.keymap.del("n", "gri")
vim.keymap.del("n", "grn")
vim.keymap.del("n", "grr")
vim.keymap.del("n", "grt")
vim.keymap.del("n", "grx")
