vim.keymap.set({ "n", "t" }, "<A-w>", "<Cmd>vertical new<CR>")
vim.keymap.set({ "n", "t" }, "<A-W>", "<Cmd>new<CR>")
vim.keymap.set({ "n", "t" }, "<A-t>", "<Cmd>tab new<CR>")
vim.keymap.set({ "n", "t" }, "<A-o>", "<Cmd>only<CR>")
vim.keymap.set({ "n", "t" }, "<A-h>", "<Cmd>wincmd h<CR>")
vim.keymap.set({ "n", "t" }, "<A-j>", "<Cmd>wincmd j<CR>")
vim.keymap.set({ "n", "t" }, "<A-k>", "<Cmd>wincmd k<CR>")
vim.keymap.set({ "n", "t" }, "<A-l>", "<Cmd>wincmd l<CR>")
vim.keymap.set({ "n", "t" }, "<A-H>", "<Cmd>wincmd H<CR>")
vim.keymap.set({ "n", "t" }, "<A-J>", "<Cmd>wincmd J<CR>")
vim.keymap.set({ "n", "t" }, "<A-K>", "<Cmd>wincmd K<CR>")
vim.keymap.set({ "n", "t" }, "<A-L>", "<Cmd>wincmd L<CR>")
vim.keymap.set({ "n", "t" }, "<A-Tab>", "<Cmd>tabnext<CR>")
vim.keymap.set({ "n", "t" }, "<A-S-Tab>", "<Cmd>tabprevious<CR>")

vim.keymap.set("x", "H", "<gv")
vim.keymap.set("x", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("x", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("x", "L", ">gv")
vim.keymap.set("x", "O", ":sort<CR>")

vim.keymap.set("n", "<Space><Return>", "<Cmd>terminal<CR>i")
vim.keymap.set("t", "<A-Esc>", "<C-\\><C-n>")
vim.keymap.set("t", "<C-BS>", "<C-h>")

vim.keymap.set("n", "g0", "gg0")
vim.keymap.set("n", "gl", "<C-o>")
vim.keymap.set("n", "gq", "<Cmd>cnext<CR>")
vim.keymap.set("n", "gQ", "<Cmd>cprevious<CR>")

vim.keymap.set("!", "<C-BS>", "<C-w>")
vim.keymap.set("n", "<C-j>", "m`J``")
vim.keymap.set("n", "X", '"_D')
vim.keymap.set("n", "vv", "gv")
vim.keymap.set({ "n", "x" }, "x", '"_x')

vim.keymap.del("n", "gra")
vim.keymap.del("n", "gri")
vim.keymap.del("n", "grn")
vim.keymap.del("n", "grr")
vim.keymap.del("n", "grt")
vim.keymap.del("n", "grx")
