[gmail]
from = Pascal Diehm <pdiehm8@gmail.com>
source = imaps://pdiehm8%40gmail.com@imap.gmail.com:993
outgoing = smtps://pdiehm8%40gmail.com@smtp.gmail.com:465
source-cred-cmd = cat ~/.local/share/aerc/keys/gmail
outgoing-cred-cmd = cat ~/.local/share/aerc/keys/gmail

folders = INBOX,Sent Mail,Archive,Drafts,Spam
folders-sort = INBOX,Sent Mail,Archive,Drafts,Spam
folder-map = ~/.config/aerc/maps/gmail.conf
copy-to = Sent Mail

address-book-cmd = carddav-query -S gmail %s
carddav-source = https://pdiehm8%40gmail.com@www.googleapis.com/carddav/v1/principals/pdiehm8@gmail.com/lists/default
carddav-source-cred-cmd = cat ~/.local/share/aerc/keys/gmail

check-mail = 5m
send-as-utc = true

[uni]
from = Pascal Diehm <pascal.diehm@stud-mail.uni-wuerzburg.de>
source = imaps://s457719@imap.mail.uni-wuerzburg.de:993
outgoing = smtps://s457719@mailmaster.uni-wuerzburg.de:465
source-cred-cmd = cat ~/.local/share/aerc/keys/uni
outgoing-cred-cmd = cat ~/.local/share/aerc/keys/uni

folders = INBOX,Sent Items,Archive,Drafts,Junk Email
folders-sort = INBOX,Sent Items,Archive,Drafts,Junk Email
copy-to = Sent Items

check-mail = 5m
send-as-utc = true
address-book-cmd = carddav-query -S gmail %s
