[general]
default-save-path = ~/Downloads
pgp-provider = gpg
use-terminal-pinentry = true
unsafe-accounts-conf = true

[ui]
index-columns = "flags:4,name<20%,subject,date>="
column-flags = '{{.Flags | join ""}}'
column-name = "{{index (.From | names) 0}}"
column-subject = "{{.ThreadPrefix}}{{.SubjectBase}}"
column-date = "{{.DateAutoFormat .Date.Local}}"

timestamp-format = "02 Jan 2006"
this-day-time-format = "15:04"
this-week-time-format = "Jan 02, 15:04"
this-year-time-format = "Jan 02, 15:04"
message-view-timestamp-format = "Mon, 02 Jan 2006 15:04:05 -0700"

spinner = ",,,,,"
spinner-interval = 80ms

icon-encrypted = ""
icon-signed = ""
icon-unknown = ""
icon-invalid = ""
icon-attachment = ""
icon-new = ""
icon-old = ""
icon-replied = ""
icon-forwarded = ""
icon-flagged = ""
icon-marked = "*"
icon-draft = ""
icon-deleted = ""

threading-enabled = true
show-thread-context = true
thread-prefix-tip = ""
thread-prefix-indent = " "
thread-prefix-stem = "│"
thread-prefix-limb = "─"
thread-prefix-first-child = "─"
thread-prefix-has-siblings = "├"
thread-prefix-last-sibling = "└"

[statusline]
status-columns = "left<*,center>=,right>*"
column-left = "[{{.Account}}] {{.StatusInfo}}"
column-center = "{{.TrayInfo}}"
column-right = "{{.PendingKeys}}  {{cwd}}"

[filters]
.headers = colorize
text/plain = colorize
text/html = html | colorize
text/calendar = calendar
message/delivery-status = colorize
message/rfc822 = colorize
* = bat --plain --paging always --force-colorization --file-name "$AERC_FILENAME"
