vim.keymap.set({ "n", "x", "t" }, "<A-w>", "<Cmd>vertical new<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-W>", "<Cmd>new<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-s>", "<Cmd>vertical split<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-S>", "<Cmd>split<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-t>", "<Cmd>tab new<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-T>", "<Cmd>wincmd T<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-o>", "<Cmd>wincmd o<CR>")

vim.keymap.set({ "n", "x", "t" }, "<A-h>", "<Cmd>wincmd h<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-j>", "<Cmd>wincmd j<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-k>", "<Cmd>wincmd k<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-l>", "<Cmd>wincmd l<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-H>", "<Cmd>wincmd H<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-J>", "<Cmd>wincmd J<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-K>", "<Cmd>wincmd K<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-L>", "<Cmd>wincmd L<CR>")

vim.keymap.set({ "n", "x", "t" }, "<C-A-h>", "<Cmd>wincmd <<CR>")
vim.keymap.set({ "n", "x", "t" }, "<C-A-l>", "<Cmd>wincmd ><CR>")
vim.keymap.set({ "n", "x", "t" }, "<C-A-j>", "<Cmd>wincmd -<CR>")
vim.keymap.set({ "n", "x", "t" }, "<C-A-k>", "<Cmd>wincmd +<CR>")
vim.keymap.set({ "n", "x", "t" }, "<C-A-Space>", "<Cmd>wincmd =<CR>")

vim.keymap.set({ "n", "x", "t" }, "<A-Tab>", "<Cmd>tabnext<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-S-Tab>", "<Cmd>tabprevious<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-1>", "<Cmd>tabnext 1<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-2>", "<Cmd>tabnext 2<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-3>", "<Cmd>tabnext 3<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-4>", "<Cmd>tabnext 4<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-5>", "<Cmd>tabnext 5<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-6>", "<Cmd>tabnext 6<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-7>", "<Cmd>tabnext 7<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-8>", "<Cmd>tabnext 8<CR>")
vim.keymap.set({ "n", "x", "t" }, "<A-9>", "<Cmd>tabnext 9<CR>")
